### PR TITLE
More syllable rules

### LINKED ISSUE #2: Unexpected syllables for several examples
text: `he's got a document`
expected: 6 total
actual: 

```
[ [ [ 'he\'he\'s' ],
[],
[ 'got' ],
[ 'a' ],
[ 'doc', 'um', 'en', 't' ] ] ]
```

Looks like `he's` and `document` are coming out wrong

### PR DESCRIPTION
**Pull request by factormystic**
Opening this PR now to make you aware of it. I'm still chipping away at it.

todo:
- [x] more test cases & more precise assertion
- [x] fix #2 (`do cu ment`, `some thing`)
- [x] fix https://github.com/nlp-compromise/nlp_compromise/issues/130 (`eu lo gy`)
- [x] fix trailing consonants not being attached to previous syllables (`reasons` is bugged as `rea son s`, `and` is bugged as `an d`)
- ~~figure out how to interpret `-shed` words (`finished`, `unpolished`, `crashed`)~~
  - do this in another branch

### CODE REVIEW

**Comment by spencermountain** [comment]
yes! go nuts. 
let me know when i can pull-er in

**Comment by spencermountain** [comment]
_nudge_ :wink: *nudge

**Comment by factormystic** [comment]
Okay this branch is now complete. However there's a merge conflict since #5. I can update this branch to remove let/const, however, wouldn't it be better to put this code through an ES5 transformation build step, so the source can still use let/const?

**Comment by factormystic** [comment]
Basically I'm saying #4 was a mistake...

**Comment by spencermountain** [comment]
ah, this is brilliant. thank you.
yeah, I don't mind monkeying around with different build ideas. No sweats.
I'm no git-master, but happy to force-merge this, or whatever it's called. That cool?

**Comment by factormystic** [comment]
Well if you merge it in now, it'll effectively revert the other two pr's, since I am using let/const, so as-is, this project will break in browsers. What I'm saying is there's basically two options: I can add a commit to replace let/const with var, here in this branch, or the es5 build process can be restored. I'm okay either way.

**Comment by factormystic** [comment]
But anyway if you are fine returning to a build process, then yes this can be merged

**Comment by spencermountain** [comment]
got it. thanks!

**Pull request merged**
